module.exports = {

  GOOGLE_SIGNIN_IOS_KEY : '969221018354-ft425jdl1au389o12h0s2lf85rdc94fc.apps.googleusercontent.com',
  GOOGLE_SIGNIN_WEB_KEY : '969221018354-409nd11ahj03tvu3r4mts2rq4fmu8fbh.apps.googleusercontent.com',
  LOGIN_TYPE : 'LOGIN_TYPE',
  FACEBOOK_LOGIN : 'FACEBOOK_LOGIN',
  GOOGLE_LOGIN : 'GOOGLE_LOGIN',
  EMAIL_LOGIN : 'EMAIL_LOGIN',
  API_TOKEN : 'APITOKEN',
  FB_TOKEN : 'FBTOKEN',
  API_TOKEN_EXPIRATION : 'API_TOKEN_EXPIRATION',
  USER_ID : 'USERID',
  FB_USER_ID : 'FB_USER',
  FB_USER_NAME : "FB_USER_NAME",
  FB_USER_EMAIL : "FB_USER_EMAIL",
  FB_USER_IMAGE : "FB_USER_IMAGE",
  PASSWORD : 'PASSWORD',
  API_URL : 'http://54.93.147.210/api'
};
